namespace DocRedactorEngine
{
    [default_interface]
    runtimeclass XpsParser
    {
        XpsParser();
        Int32 MyProperty;
        String Greeting();
        Windows.Foundation.IAsyncOperation<XpsParseResult> ParseAsync(Windows.Storage.StorageFile file);
    }

    [default_interface]
    runtimeclass TextSegment
    {
        TextSegment();
        String Text{ get; };
        Int32 PageIndex{ get; };
        Single OriginX{ get; };
        Single OriginY{ get; };
        Single Width{ get; };
        Single Height{ get; };
        Single FontSize{ get; };
    }

    [default_interface]
    runtimeclass PageInfo
    {
        PageInfo();
        Int32 PageIndex{ get; };
        Single Width{ get; };
        Single Height{ get; };
    }

    [default_interface]
    runtimeclass XpsParseResult
    {
        XpsParseResult();
        Windows.Foundation.Collections.IVectorView<TextSegment> Segments{ get; };
        Windows.Foundation.Collections.IVectorView<PageInfo> Pages{ get; };
    }

    [default_interface]
    runtimeclass PiiMatch
    {
        PiiMatch();
        String Text{ get; };
        Int32 Category{ get; };
        String CategoryName{ get; };
        Int32 SegmentIndex{ get; };
        Int32 PositionInSegment{ get; };
        Int32 Length{ get; };
        Int32 PageIndex{ get; };
        Single OriginX{ get; };
        Single OriginY{ get; };
        Single Width{ get; };
        Single Height{ get; };
    }

    [default_interface]
    runtimeclass PiiDetector
    {
        PiiDetector();
        Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IVectorView<PiiMatch> > DetectAsync(Windows.Foundation.Collections.IVectorView<TextSegment> segments);

        static String MaskText(String original, Int32 category);
    }

    [default_interface]
    runtimeclass Redactor
    {
        Redactor();
        Windows.Foundation.IAsyncOperation<Boolean> RedactAsync(Windows.Storage.StorageFile inputFile, Windows.Storage.StorageFile outputFile, Windows.Foundation.Collections.IVectorView<PiiMatch> matches);
    }
}